#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;

require __DIR__ . '/vendor/autoload.php';

// Tạo instance ứng dụng
$app = require_once __DIR__ . '/bootstrap/app.php';

// Khởi chạy Artisan
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);
